---

- name: Get facts about nic
  ansible.builtin.set_fact:
    e1000e_nics: "{{ ansible_facts | dict2items |
                    selectattr('value.module', 'defined') |
                    selectattr('value.module', 'equalto', 'e1000e') |
                    map(attribute='key') | list }}"

- name: Template scripts
  ansible.builtin.template:
    src: "{{ role_path }}/templates/nic-script.sh.j2"
    dest: /etc/systemd/system/{{ item }}-fix.sh
    mode: "0744"
  vars:
    target_nic: "{{ item }}"
  register: scripts_written
  loop: "{{ e1000e_nics }}"

- name: Template systemd service files
  ansible.builtin.template:
    src: "{{ role_path }}/templates/e1000e-fix.service.j2"
    dest: /etc/systemd/system/{{ item }}-fix.service
    mode: "0644"
  vars:
    target_nic: "{{ item }}"
  register: templates_written
  loop: "{{ e1000e_nics }}"

- name: Restart and enable systemd service
  ansible.builtin.systemd_service:
    name: "{{ item }}-fix.service"
    state: restarted
    enabled: true
    daemon_reload: true
  loop: "{{ e1000e_nics }}"
  when: "scripts_written.changed or templates_written.changed"
